-- MySQL Script generated by MySQL Workbench
-- Mon Feb 26 22:54:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ksiegarnia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ksiegarnia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ksiegarnia` DEFAULT CHARACTER SET utf8 ;
USE `ksiegarnia` ;

-- -----------------------------------------------------
-- Table `ksiegarnia`.`stanowisko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksiegarnia`.`stanowisko` (
  `id_stanowisko` INT NOT NULL AUTO_INCREMENT,
  `nazwa_stanowisko` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_stanowisko`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksiegarnia`.`dzial_pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksiegarnia`.`dzial_pracownik` (
  `id_dzial_pracownik` INT NOT NULL AUTO_INCREMENT,
  `nazwa_dzial_pracownik` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dzial_pracownik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksiegarnia`.`pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksiegarnia`.`pracownik` (
  `id_pracownik` INT NOT NULL AUTO_INCREMENT,
  `imie_pracownik` VARCHAR(45) NOT NULL,
  `nazwisko_pracownik` VARCHAR(45) NOT NULL,
  `data_zatrudnienia` VARCHAR(45) NOT NULL,
  `data_zwolnienia` VARCHAR(45) NULL,
  `pensja` FLOAT NOT NULL,
  `numer_telefonu` INT NULL,
  `stanowisko_id_stanowisko` INT NOT NULL,
  `dzial_pracownik_id_dzial_pracownik` INT NOT NULL,
  PRIMARY KEY (`id_pracownik`, `stanowisko_id_stanowisko`, `dzial_pracownik_id_dzial_pracownik`),
  INDEX `fk_pracownik_stanowisko_idx` (`stanowisko_id_stanowisko` ASC),
  INDEX `fk_pracownik_dzial_pracownik1_idx` (`dzial_pracownik_id_dzial_pracownik` ASC),
  CONSTRAINT `fk_pracownik_stanowisko`
    FOREIGN KEY (`stanowisko_id_stanowisko`)
    REFERENCES `ksiegarnia`.`stanowisko` (`id_stanowisko`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pracownik_dzial_pracownik1`
    FOREIGN KEY (`dzial_pracownik_id_dzial_pracownik`)
    REFERENCES `ksiegarnia`.`dzial_pracownik` (`id_dzial_pracownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksiegarnia`.`dostawa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksiegarnia`.`dostawa` (
  `id_dostawa` INT NOT NULL AUTO_INCREMENT,
  `nazwa_dostawa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_dostawa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksiegarnia`.`klient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksiegarnia`.`klient` (
  `id_klient` INT NOT NULL AUTO_INCREMENT,
  `imie_klient` VARCHAR(45) NOT NULL,
  `nazwisko_klient` VARCHAR(45) NOT NULL,
  `ulica_klient` VARCHAR(45) NOT NULL,
  `kod_pocztowy_klient` INT NOT NULL,
  `miasto_klient` VARCHAR(45) NOT NULL,
  `nr_telefonu` INT NOT NULL,
  PRIMARY KEY (`id_klient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksiegarnia`.`zamowienie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksiegarnia`.`zamowienie` (
  `id_zamowienie` INT NOT NULL AUTO_INCREMENT,
  `ulica_dostawy` VARCHAR(45) NOT NULL,
  `miasto_dostawy` VARCHAR(45) NOT NULL,
  `kod_pocztowy_dostawy` INT NOT NULL,
  `faktura` TINYINT NOT NULL,
  `numer_zamowienia` VARCHAR(45) NOT NULL,
  `pracownik_id_pracownik` INT NOT NULL,
  `dostawa_id_dostawa` INT NOT NULL,
  `klient_id_klient` INT NOT NULL,
  PRIMARY KEY (`id_zamowienie`, `pracownik_id_pracownik`, `dostawa_id_dostawa`, `klient_id_klient`),
  INDEX `fk_zamowienie_pracownik1_idx` (`pracownik_id_pracownik` ASC),
  INDEX `fk_zamowienie_dostawa1_idx` (`dostawa_id_dostawa` ASC),
  INDEX `fk_zamowienie_klient1_idx` (`klient_id_klient` ASC),
  CONSTRAINT `fk_zamowienie_pracownik1`
    FOREIGN KEY (`pracownik_id_pracownik`)
    REFERENCES `ksiegarnia`.`pracownik` (`id_pracownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienie_dostawa1`
    FOREIGN KEY (`dostawa_id_dostawa`)
    REFERENCES `ksiegarnia`.`dostawa` (`id_dostawa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienie_klient1`
    FOREIGN KEY (`klient_id_klient`)
    REFERENCES `ksiegarnia`.`klient` (`id_klient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksiegarnia`.`kategoria_ksiazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksiegarnia`.`kategoria_ksiazka` (
  `id_kategoria_ksiazki` INT NOT NULL AUTO_INCREMENT,
  `nazwa_kategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_kategoria_ksiazki`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksiegarnia`.`ksiazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksiegarnia`.`ksiazka` (
  `id_ksiazki` INT NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(45) NULL,
  `rok_wydania` VARCHAR(45) NOT NULL,
  `numer_isbn` TEXT(17) NULL,
  `kategoria_ksiazki_id_kategoria_ksiazki` INT NOT NULL,
  PRIMARY KEY (`id_ksiazki`, `kategoria_ksiazki_id_kategoria_ksiazki`),
  INDEX `fk_ksiazki_kategoria_ksiazki1_idx` (`kategoria_ksiazki_id_kategoria_ksiazki` ASC),
  CONSTRAINT `fk_ksiazki_kategoria_ksiazki1`
    FOREIGN KEY (`kategoria_ksiazki_id_kategoria_ksiazki`)
    REFERENCES `ksiegarnia`.`kategoria_ksiazka` (`id_kategoria_ksiazki`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksiegarnia`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksiegarnia`.`autor` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `imie_autor` VARCHAR(45) NOT NULL,
  `nazwisko_autor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksiegarnia`.`autor_has_ksiazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksiegarnia`.`autor_has_ksiazka` (
  `autor_id_autor` INT NOT NULL,
  `ksiazki_id_ksiazki` INT NOT NULL,
  PRIMARY KEY (`autor_id_autor`, `ksiazki_id_ksiazki`),
  INDEX `fk_autor_has_ksiazki_ksiazki1_idx` (`ksiazki_id_ksiazki` ASC),
  INDEX `fk_autor_has_ksiazki_autor1_idx` (`autor_id_autor` ASC),
  CONSTRAINT `fk_autor_has_ksiazki_autor1`
    FOREIGN KEY (`autor_id_autor`)
    REFERENCES `ksiegarnia`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autor_has_ksiazki_ksiazki1`
    FOREIGN KEY (`ksiazki_id_ksiazki`)
    REFERENCES `ksiegarnia`.`ksiazka` (`id_ksiazki`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksiegarnia`.`zamowienie_has_ksiazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksiegarnia`.`zamowienie_has_ksiazka` (
  `zamowienie_id_zamowienie` INT NOT NULL,
  `ksiazki_id_ksiazki` INT NOT NULL,
  PRIMARY KEY (`zamowienie_id_zamowienie`, `ksiazki_id_ksiazki`),
  INDEX `fk_zamowienie_has_ksiazki_ksiazki1_idx` (`ksiazki_id_ksiazki` ASC),
  INDEX `fk_zamowienie_has_ksiazki_zamowienie1_idx` (`zamowienie_id_zamowienie` ASC),
  CONSTRAINT `fk_zamowienie_has_ksiazki_zamowienie1`
    FOREIGN KEY (`zamowienie_id_zamowienie`)
    REFERENCES `ksiegarnia`.`zamowienie` (`id_zamowienie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienie_has_ksiazki_ksiazki1`
    FOREIGN KEY (`ksiazki_id_ksiazki`)
    REFERENCES `ksiegarnia`.`ksiazka` (`id_ksiazki`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
